[package]
name = "web-server-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = "0.4.22"
rand = "0.8.5"
regex = "1.6.0"
rust-embed = "6.4.1"
